### ISSUE TITLE
evalv3: field unexpectedly allowed with struct disjunction

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3606]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0b06bd543bc422ab11be058443a271a6596151ab
</pre>

### Does this issue reproduce with the latest stable release?

Yes, back at least as far as v0.9.2

### What did you do?

```
env CUE_EXPERIMENT=evalv3
! exec cue vet x.cue

-- x.cue --
data: {
	notAllowed: true
} & #S

#S: string | {}
```

### What did you expect to see?

Passing test. The empty struct inside `#S` should be closed, not allowing any extra fields.

### What did you see instead?

```
> env CUE_EXPERIMENT=evalv3
> ! exec cue vet x.cue
FAIL: /tmp/x.txtar:2: unexpected command success
```

**Comment by mpvl** [comment]
This seems to have been fixed already.

**Comment by myitcv** [comment]
@mpvl - I've just tested against f99441ac39a2 and I still see this problem. i.e. @rogpeppe's repro test fails, when it should pass.
